import './components/filter.js'
import './components/table.js'
import './components/header.js'
import './components/main.js'
import './components/crud.js'
import './components/modal-destroy.js'
import './components/title.js'
import './components/menu.js'
import './components/upload-image.js'
import './components/notification.js'
import './components/image-gallery.js'
import './components/page.js'
import './components/forms/user.js'
import './components/forms/customer.js'
import './components/forms/company.js'
import './components/forms/product-category.js'
import './components/forms/product.js'


