import './components/page.js'
import './components/logo.js'
import './components/header-component.js'
import './components/menu-component.js'
import './components/title-component.js'
import './components/font-loader-component.js'
import './components/products-component.js'
